
# https://docs.travis-ci.com/user/reference/trusty
dist: trusty
sudo: false

# https://docs.travis-ci.com/user/languages/php/
language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

# https://docs.travis-ci.com/user/customizing-the-build/
before_script:
  - if [[ -n "$CODACY_PROJECT_TOKEN" ]]; then
        composer require codacy/coverage -n ;
    else
        composer install -n ;
    fi

script:
  - if [[ -n "$CODACY_PROJECT_TOKEN" ]]; then
        vendor/bin/phpunit --coverage-clover build/coverage/xml ;
    else
        vendor/bin/phpunit ;
    fi

after_script:
  - if [[ -n "$CODACY_PROJECT_TOKEN" ]]; then
        vendor/bin/codacycoverage clover build/coverage/xml ;
    fi
